# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and release BEX

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - run: yarn run build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-zipped
        path: dist/bex/Packaged.deck20.zip

  release:
    
    needs: build
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Update CHANGELOG
      id: changelog
      uses: requarks/changelog-action@v1
      with:
        token: ${{ github.token }}
        tag: ${{ github.ref_name }}
        writeToFile: false
        includeInvalidCommits: true
        excludeTypes: docs,style

    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: dist-zipped
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body: ${{ steps.changelog.outputs.changes }}
        files:
          Packaged.deck20.zip
