# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and release BEX

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - run: yarn run build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-zipped
        path: dist/bex/Packaged.deck20.zip

  release:
    
    needs: build
    runs-on: ubuntu-latest
  
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: dist-zipped
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          Packaged.deck20.zip
